name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - matplotlib
  - pandas
  - scipy
  - ipywidgets
  - voila
  - bqplot
  - ipympl
  - ipyvolume
  - streamlit
