presentation_folder: 90_Streamlit_apps/MWW01/SlideJet_Presentations/SJ_DATA/GWBmC_WS2526_T03_Stroemungsmodellierung1
header_text: GWBmC_WS2526_T03_Stroemungsmodellierung1
subheader_text: Interactive Slideshow
